name: Build and deploy (Vite) to GitHub Pages (gh-pages)

on:
  push:
    branches: [ "main" ]       # spusť při pushi do main
  workflow_dispatch:            # možnost spustit ručně

# nutné pro push do větve gh-pages
permissions:
  contents: write
  pages: write
  id-token: write

# nerozbíhej paralelně víc deployů
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build production (Vite)
        run: npm run build

      # pro SPA routing na GitHub Pages (deep linky fungují)
      - name: Create 404 for SPA routing
        run: cp ./dist/index.html ./dist/404.html

      # nasazení obsahu ./dist do větve gh-pages + vytvoření CNAME
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          cname: "trenerkakaci.cz"
